export const SET_SPOTIFY_TOKENS = 'SET_SPOTIFY_TOKENS';
export const CLEAR_SPOTIFY_TOKENS = 'CLEAR_SPOTIFY_TOKENS';

export const FETCH_ME = 'FETCH_ME';
export const FETCH_TOP_TRACKS = 'FETCH_TOP_TRACKS';
export const FETCH_TOP_ARTISTS = 'FETCH_TOP_ARTISTS';
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
